"""Ambient request context, propagated across async boundaries.

The correlation id is generated by API middleware, travels with every log event,
and is copied into the worker job payload -- which is what makes an ingestion
trace joinable to the upload request that caused it. Without that, the two
processes produce two unrelated piles of logs.

:mod:`contextvars` rather than a parameter threaded through every call: an
argument that exists only to be passed along ends up dropped somewhere, and
context vars are correctly isolated per task under :mod:`asyncio`.
"""

from __future__ import annotations

import uuid
from contextvars import ContextVar
from dataclasses import dataclass, fields

__all__ = [
    "RequestContext",
    "bind_request_context",
    "clear_request_context",
    "current_request_context",
    "new_correlation_id",
]


@dataclass(frozen=True, slots=True)
class RequestContext:
    """Identifiers describing the work currently in flight.

    Attributes:
        correlation_id: Ties together every event caused by one user action,
            including work that happens later in the ingestion worker.
        tenant_id: The tenant the work belongs to.
        request_id: Identifies a single HTTP request, where a correlation may
            span several.
    """

    correlation_id: str | None = None
    tenant_id: str | None = None
    request_id: str | None = None

    def as_payload(self) -> dict[str, str]:
        """Render the context for a job payload or a log event.

        Unset values are omitted rather than emitted as ``None``. A null
        correlation id on every event is noise that hides the real ones.

        Returns:
            The bound values only.
        """
        return {
            field.name: value
            for field in fields(self)
            if isinstance(value := getattr(self, field.name), str)
        }


_CONTEXT: ContextVar[RequestContext] = ContextVar("rag_request_context")


def new_correlation_id() -> str:
    """Generate a fresh correlation id.

    Returns:
        A unique identifier suitable for tracing one user action end to end.
    """
    return uuid.uuid4().hex


def current_request_context() -> RequestContext:
    """Read the context bound to the current task.

    Returns:
        The bound context, or an empty one when nothing has been bound.
    """
    return _CONTEXT.get(RequestContext())


def bind_request_context(
    *,
    correlation_id: str | None = None,
    tenant_id: str | None = None,
    request_id: str | None = None,
) -> RequestContext:
    """Bind or update identifiers for the current task.

    Fields left as ``None`` keep whatever value is already bound, so middleware
    can set the correlation id and an authentication dependency can add the
    tenant later without the two having to know about each other.

    Args:
        correlation_id: Correlation to bind, if any.
        tenant_id: Tenant to bind, if any.
        request_id: Request id to bind, if any.

    Returns:
        The resulting context.
    """
    existing = current_request_context()
    updated = RequestContext(
        correlation_id=correlation_id if correlation_id is not None else existing.correlation_id,
        tenant_id=tenant_id if tenant_id is not None else existing.tenant_id,
        request_id=request_id if request_id is not None else existing.request_id,
    )
    _CONTEXT.set(updated)
    return updated


def clear_request_context() -> None:
    """Discard any bound context.

    Used at the end of a request and by tests, so state cannot leak between
    units of work sharing a thread.
    """
    _CONTEXT.set(RequestContext())
